services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./Database/dummy_data.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  backend:
    build: ./Backend
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=8080
      - NODE_ENV=dev
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
  frontend:
    build: ./FrontEnd
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    ports:
      - "80:80"