services:
  - name: backend
    type: web
    env: node
    buildCommand: "npm ci"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production

  - name: frontend
    type: static
    buildCommand: "npm ci && npm run build"
    staticPublishPath: build
